name: Update Changelog on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  update-changelog:
    if: >
      github.event.pull_request.merged == true &&
      github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Prepend to Changelog
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_BODY: ${{ github.event.pull_request.body }}
          MERGED_AT: ${{ github.event.pull_request.merged_at }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          TIMESTAMP=$(date -d "$MERGED_AT" +'%d/%m/%Y')

          # Convert markdown-style list items into indented changelog lines
          FORMATTED_BODY=$(echo "$PR_BODY" | sed 's/^[[:space:]]\{2,\}- /        /; s/^- /    /')

          # Create the new entry content in a variable
          NEW_ENTRY=$(cat <<EOF
          ${TIMESTAMP} - ${PR_AUTHOR} (#${PR_NUMBER})
          $FORMATTED_BODY
          EOF
          )

          # If the changelog exists, prepend the new entry with a separating newline.
          # Otherwise, just create the file with the new entry.
          if [ -f "source/Changelog.txt" ]; then
            echo -e "$NEW_ENTRY\n" | cat - source/Changelog.txt > temp_changelog.txt && mv temp_changelog.txt source/Changelog.txt
          else
            echo -e "$NEW_ENTRY" > source/Changelog.txt
          fi

      - name: Create Pull Request with Changelog Update
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs(changelog): Update Changelog.txt from PR #${{ github.event.pull_request.number }}"
          title: "Docs: Update Changelog for #${{ github.event.pull_request.number }}"
          body: "Automated changelog update. This PR will be auto-merged."
          branch: "changelog/pr-${{ github.event.pull_request.number }}"
          base: ${{ github.event.pull_request.base.ref }}

      - name: Enable Auto-Merge via GitHub CLI
        if: steps.cpr.outputs.pull-request-number
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}